# Generated by Django 2.0.2 on 2018-07-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='category',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='category',
            field=models.ManyToManyField(to='tutorial.Category', verbose_name='カテゴリ'),
        ),
    ]
