# Generated by Django 2.0.2 on 2018-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20180708_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='star',
            field=models.IntegerField(blank=True, verbose_name='スター'),
        ),
    ]
