# Generated by Django 2.0.2 on 2018-07-09 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20180708_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=30, verbose_name='お名前')),
                ('text', models.TextField(verbose_name='本文')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutorial.Tutorial', verbose_name='紐づくチュートリアル')),
            ],
        ),
    ]
