# Generated by Django 2.0.2 on 2018-07-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='name',
            new_name='title',
        ),
    ]
