# Generated by Django 2.0.2 on 2018-07-16 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorial', '0007_auto_20180717_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='カテゴリ'),
        ),
    ]
