# Generated by Django 2.0.2 on 2018-07-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='social',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='social',
            name='user',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
